apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: tamboot-admin-back-app
    environment: product
    tier: backend
  name: tamboot-admin-back-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tamboot-admin-back-app
  template:
    metadata:
      labels:
        app: tamboot-admin-back-app
    spec:
      containers:
      - command:
        - java
        - '-Xms64m'
        - '-Xmx256m'
        - '-jar'
        - app.jar
        env:
        - name: LANG
          value: C.UTF-8
        - name: JAVA_HOME
          value: /usr/lib/jvm/java-1.8-openjdk
        image: >-
          registry-vpc.cn-shenzhen.aliyuncs.com/registry_tam/tamboot-admin-back:1.4.0.RELEASE
        imagePullPolicy: Always
        name: tamboot-admin-back-app
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: volume-tmp
        - mountPath: /usr/local/app/config
          name: volume-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: volume-tmp
      - configMap:
          defaultMode: 420
          name: tamboot-admin-back-config
        name: volume-config

---
apiVersion: v1
kind: Service
metadata:
  name: tamboot-admin-back-service
  namespace: default
spec:
  ports:
  - name: tamboot-admin-back-service
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tamboot-admin-back-app
  sessionAffinity: None
  type: ClusterIP
