spring:
  transaction:
    rollback-on-commit-failure: true
  security:
    useRedisRepo: true
    loginPath: /login
    ignoringAntMatchers:
      - /public/**
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tamboot_admin_db?useUnicode=true&characterEncoding=utf-8&&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    username: root
    password: Aa123456
    hikari:
      maximum-pool-size: 15
      max-lifetime: 1800000
      connection-timeout: 30000
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  ignoreInterceptor: false
  throwVersionLockException: true
  snowFlake:
    machineId: 0
  configuration:
    mapUnderscoreToCamelCase: true
server:
  servlet:
    context-path: /tamboot-admin
  port: 8080